install.sh
is a first step in using cantera simulations to validate generated models by comparing model observables (eg speciation data, ignition delays, etc...-) rather than model details, which is the current state.
cantera is installed via bryan weber's anaconda channel. Currently installs v2.2.1
[Here](https://github.com/Cantera/cantera/issues/261#issuecomment-167114919) it is discussed how cantera can be installed via anaconda.
=> install cantera during travis build

examples/rmg/diesel/input.py, examples/rmg/e85/input.py, examples/rmg/eg2/input.py, examples/rmg/ethane_sensitivity/input.py, examples/rmg/mfmt/input.py
These 4 cases will run much longer than any previous ones, and should preferably not be run in the context of continuous integration.
They could instead be used to monitor resource usage and performance characteristics.
=> Add longer simulation cases

before_install.sh, install.sh
This PR:
1) fetches a stable version of miniconda rather than the latest, which can be updated by external parties without us knowing.
2) reverts previous PR #19 by updating the installed conda.
3) changes the way the "tested" environment is named in case it is created from within the RMG-Py repo.
=> Misc. conda fixes

install.sh
There's been requests that RMG-tests could test cases where both RMG-Py and RMG-databse are new (non-master branches) since often times people are making changes in RMG-Py and RMG-database to deliver certain functionality (i.e., polycyclic, nitrogen atomtypes, etc.).
This PR makes that purpose of testing possible. Developers only need to modify `deploy.sh` in RMG-Py (see an [example](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/8b0eb4d37b68b573d513176174bd3a29b48ecc2f)) to notify RMG-tests it's a special test case.
=> enable RMG-tests to test cases where both Py and db are non-master branches

examples/rmg/NC/input.py
NC job runs very slow after new nitrogen atomtype is introduced. This PR is to loosen the convergence tolerance so that travis can finish the job.
=> make NC example easier to finish

examples/rmg/NC/input.py, examples/rmg/NC/regression_input.py
This PR tries to
- add regression test back for NC which was disabled before for static benchmark reason
- saves edge for NC so that RMG-tests can compare edge between benchmark and testing versions
=> Fix NC test example

local_tests/exe.sh, local_tests/input.sh
In order to reduce user input, the OS info can be extracted directly from MACHTYPE.
=> detect OS from MACHTYPE instead of user input

README.md, local_tests/run.sl, local_tests/submit_parallel.sl, local_tests/submit_serial.sl, version_summary.sh
This PR adds two submission scripts for slurm scheduler system.
after modify `input.sh`, run
```bash
sbatch submit_serial.sl
```
after modify `input.sh`, run
```bash
sbatch submit_parallel.sl $(pwd)
```
=> Provide example slurm submission scripts

local_tests/clean_up.sh, run.sh
Previously the rmgrc file which directs RMG-Py to the appropriate location of RMG-database was stored in /HOME/.rmg/.rmgrc. This is dangerous because if a local run of RMG-tests does not complete, the rmgrc will still build to either the benchmark or test version of RMG-database, possibly without the user's knowledge. Afterwards, the user may run RMG and unintentionally use the wrong pathway to RMG-database.
It was found that RMG-Py will default to looking for RMG-database relative to its own position if nothing is provided. Because the local run of RMG-tests naturally sets up RMG-database this way for both bechmark and test builds, it is not necessary to ever set the rmgrc.
=> Removed setting the rmgrc file for benchmark and test builds

run.sh
when RMG-Py change only or RMG-database change only, RMG-tests will use
same RMG-database or RMG-Py (respectively) as benchmark for testing.
In those cases, we do need rmgrc to clarify which RMG-database to use.
=> Update rmgrc in cases where benchmark and testing share RMG-Py or RMG-database

examples/rmg/MCH/input.py
Previously the MCH example used a rxn library that is now deprecated. This changes it to the new location of the the equivalent library.
=> Change KlippensteinH2O2 to new BurkeH2O2inN library for MCH example

README.md
This PR updates documentation of running RMG-tests
- local_tests execution script has been changed, now updated with correct name
- database access authentication info needed for thermo validation tests
=> update documentation of running RMG-tests locally

examples/rmg/methane/input.py
This PR modifies the methane example so that nitrogen polymer won't be generated see #55
=> add nitrogen constraint for methane example

install.sh
Detailed explanation can be found at ReactionMechanismGenerator/RMG-Py#1255.
This should address the errors with Travis builds.
=> Add quiet flag to conda env create for Travis builds

thermo_val/model.py
generate_resonance_isomers used to be called generateResonanceIsomers.
This commit fixes the name of the method on RMG-tests
=> Updated name for generate_resonance_isomers

thermo_val/model.py
The previous commit used generate_resonance_isomers.
The current name is generate_resonance_structures, which
this commit changes it to.
=> Corrected method name

examples/thermo_val/n_cyclics/dataset.txt, examples/thermo_val/rmg_internal_hetero/dataset.txt, local_tests/exe.sh
This PR adds more datasets for thermo regression testing. mainly added three datasets
- N_cyclic_table: from 134k
- agd_nitrogen_6_table: from Alon's calculations
- rg_sulfur_195_table: from Ryan's calculations
- rmg_cl_table: from Zach's database `chlorine` PR
Can be pulled in after RMG-Py `chargedAT` and `chlorine` is merged.
=> New data test

.gitignore, install.sh
For the Python 3 transition, we switch to a single `environment.yml` file, so this allows RMG-tests to work for both RMG 2 and RMG 3.
=> Changes to environment file handling

.travis.yml
The installation step takes 20 minutes, and I don't think is needed to run the final cleanup script
to signal success.
=> Skip the (slow) installation before running the finish stage

install.sh
The Superminimal regression test fails because the MOPAC license wasn't properly installed in the install.sh script.
The error given from [this](https://pipelines.actions.githubusercontent.com/c9MOlUpqlxk17onyPH01JTuKKNTQPQin1AX5Ki4pfsARtlUM7K/_apis/pipelines/1/runs/84/signedlogcontent/2?urlExpires=2021-11-16T15%3A25%3A05.6115362Z&urlSigningMethod=HMACV1&urlSignature=RtePjl%2BWvdjjbzHnUFx695ngXLuURMBPdQGmPEIfwU8%3D) Github Actions log file:
```
yes 'Yes' | $BASE_DIR/miniconda/envs/benchmark/bin/mopac $MOPACKEY > /dev/null
./install.sh: line 129: /home/runner/work/RMG-tests/RMG-tests/miniconda/envs/benchmark/bin/mopac: No such file or directory
```
It looks like this was just because the path to the mopac bin file was wrong. The base folder should be 
`/usr/share/miniconda/envs/benchmark` …
=> Fix path to MOPAC executable
